export const LIST_LOAD_DATA = 'LIST_LOAD_DATA';
export const LIST_DATA_LOADED = 'LIST_DATA_LOADED';
export const LIST_SET_QUERY_STRING = 'LIST_SET_QUERY_STRING';
export const LIST_SET_FETCHING = 'LIST_SET_FETCHING';
export const LIST_SET_ERROR = 'LIST_SET_ERROR';
export const LIST_SET_SORT = 'LIST_SET_SORT';
